baseURL      = 'http://migueldeoleiros.github.io/'
languageCode = 'en-us'
title        = 'MiguelDeOleiros personal blog'
theme        = 'hello-friend-ml'

[params]
    dateform        = "Jan 2, 2006"
    dateformShort   = "Jan 2"
    dateformNum     = "2006-01-02"
    dateformNumTime = "2006-01-02 15:04"

    description = "MiguelDeOleiros personal blog"

    # Subtitle for home
    homeSubtitle = "Software Engineer and Linux Enthusiast"

    # Set disableReadOtherPosts to true in order to hide the links to other posts.
    disableReadOtherPosts = false

    # Enable sharing buttons, if you like
    enableSharingButtons = true

    enableThemeToggle = true

    author = "Miguel L贸pez L贸pez"

    [params.logo]
        logoText = "/home/migueldeoleiros/"
        logoHomeLink = "/"
        # or
        #
        # path = "/img/your-example-logo.svg"
        # alt = "Your example logo alt text"

    [params.portrait]
        path     = "/images/profile.png"
        alt      = "logo"
        maxWidth = "150px"

    # Social icons
    [[params.social]]
        name = "github"
        url = "https://github.com/migueldeoleiros"

    [[params.social]]
        name = "email"
        url = "mailto:migueldeoleiros@gmail.com"

    [[params.social]]
        name = "linkedin"
        url = "https://www.linkedin.com/in/migueldeoleiros"

[pagination]
    pagersize = 10

[taxonomies]
    category = "blog"
    tag      = "tags"
    series   = "series"

[languages]
    [languages.en]
        title = "Miguel L贸pez L贸pez"
        subtitle = ""
        keywords = ""
        copyright = '<a href="https://creativecommons.org/licenses/by-nc/4.0/" target="_blank" rel="noopener">CC BY-NC 4.0</a>'
        readOtherPosts = "Read other posts"

    [[menu.main]]
        identifier = "2-posts"
        name       = "Posts"
        url        = "/posts"

    [[menu.main]]
        identifier = "1-wiki"
        name       = "Wiki"
        url        = "https://wiki.migueldeoleiros.com/"

